AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ni-covid-scraper

  SAM Template for ni-covid-scraper

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  NICOVIDScraper:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: scraper/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Role: arn:aws:iam::018530147132:role/ni-covid-tweets
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
      Environment:
        Variables:
          TWEETER_LAMBDA: !Sub ${NICOVIDCasesTweeter.Arn}
          VACCINE_TWEETER_LAMBDA: !Sub ${NICOVIDVaccinesTweeter.Arn}
          R_TWEETER_LAMBDA: !Sub ${NICOVIDRTweeter.Arn}
          NISRA_TWEETER_LAMBDA: !Sub ${NICOVIDNISRATweeter.Arn}
          GENERIC_TWEETER_LAMBDA: !Sub ${NICOVIDGenericTweeter.Arn}
          VARIANTS_TWEETER_LAMBDA: !Sub ${NICOVIDCOGVariantsTweeter.Arn}
          CLUSTERS_TWEETER_LAMBDA: !Sub ${NICOVIDClusterTweeter.Arn}
  NICOVIDCasesTweeter:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 2048
      Timeout: 120
      Role: arn:aws:iam::018530147132:role/ni-covid-tweets
      EventInvokeConfig:
        MaximumRetryAttempts: 0
    Metadata:
      DockerTag: tweeter-tag
      DockerContext: ./
      Dockerfile: tweeter/Dockerfile
  NICOVIDVaccinesTweeter:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 2048
      Timeout: 600
      Role: arn:aws:iam::018530147132:role/ni-covid-tweets
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      ImageConfig:
        Command:
          - "vaccines_tweeter.lambda_handler"
    Metadata:
      DockerTag: tweeter-tag
      DockerContext: ./
      Dockerfile: tweeter/Dockerfile
  NICOVIDRTweeter:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 120
      Role: arn:aws:iam::018530147132:role/ni-covid-tweets
      EventInvokeConfig:
        MaximumRetryAttempts: 0
    Metadata:
      DockerTag: textract-v2
      DockerContext: ./
      Dockerfile: r-tweeter/Dockerfile
  NICOVIDClusterTweeter:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 120
      Role: arn:aws:iam::018530147132:role/ni-covid-tweets
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      MemorySize: 2048
      ImageConfig:
        Command:
          - "cluster_tweeter.lambda_handler"
    Metadata:
      DockerTag: textract-v2
      DockerContext: ./
      Dockerfile: r-tweeter/Dockerfile
  NICOVIDNISRATweeter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nisra-tweeter/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 120
      Role: arn:aws:iam::018530147132:role/ni-covid-tweets
      EventInvokeConfig:
        MaximumRetryAttempts: 0
  NICOVIDGenericTweeter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generic-tweeter/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 120
      Role: arn:aws:iam::018530147132:role/ni-covid-tweets
      EventInvokeConfig:
        MaximumRetryAttempts: 0
  NICOVIDTestsCleaner:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: tests-cleaner/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 600
      Role: arn:aws:iam::018530147132:role/ni-covid-tweets
      EventInvokeConfig:
        MaximumRetryAttempts: 0
  NICOVIDCOGVariantsTweeter:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 600
      Role: arn:aws:iam::018530147132:role/ni-covid-tweets
      MemorySize: 2048
      ImageConfig:
        Command:
          - "variant_tweeter.lambda_handler"
      EventInvokeConfig:
        MaximumRetryAttempts: 0
    Metadata:
      DockerTag: tweeter-tag
      DockerContext: ./
      Dockerfile: tweeter/Dockerfile
  NICOVIDVariants:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 300
      Role: arn:aws:iam::018530147132:role/ni-covid-tweets
      MemorySize: 2048
      EventInvokeConfig:
        MaximumRetryAttempts: 0
#      Events:
#        InvocationLevel:
#          Type: Schedule
#          Properties:
#            Schedule: rate(1 hour)
    Metadata:
      DockerTag: selenium-v2
      DockerContext: ./
      Dockerfile: variants/Dockerfile
